"""
Config Schema Definition for Visual Config Editor

Defines field types, constraints, labels, and help text for all configuration sections.
"""

CONFIG_SCHEMA = {
    "location": {
        "_label": "Location Settings",
        "_description": "Geographic location for sun position calculations (polar day/night detection)",
        "_order": 1,
        "latitude": {
            "type": "number",
            "min": -90,
            "max": 90,
            "step": 0.1,
            "label": "Latitude",
            "help": "Latitude in decimal degrees (negative for South)",
        },
        "longitude": {
            "type": "number",
            "min": -180,
            "max": 180,
            "step": 0.1,
            "label": "Longitude",
            "help": "Longitude in decimal degrees (negative for West)",
        },
        "timezone": {
            "type": "text",
            "label": "Timezone",
            "help": "IANA timezone identifier (e.g., Europe/Oslo)",
        },
        "civil_twilight_threshold": {
            "type": "number",
            "min": -18,
            "max": 0,
            "step": 0.5,
            "label": "Civil Twilight Threshold",
            "help": "Degrees below horizon. Sun > this = force Day mode even if lux is low",
        },
    },
    "camera": {
        "_label": "Camera Settings",
        "_description": "Camera resolution, transforms, and controls",
        "_order": 2,
        "resolution": {
            "_label": "Resolution",
            "_is_object": True,
            "width": {
                "type": "number",
                "min": 640,
                "max": 4608,
                "step": 1,
                "label": "Width",
                "help": "Image width in pixels",
            },
            "height": {
                "type": "number",
                "min": 480,
                "max": 2592,
                "step": 1,
                "label": "Height",
                "help": "Image height in pixels",
            },
        },
        "transforms": {
            "_label": "Transforms",
            "_is_object": True,
            "horizontal_flip": {
                "type": "boolean",
                "label": "Horizontal Flip",
                "help": "Mirror the image horizontally",
            },
            "vertical_flip": {
                "type": "boolean",
                "label": "Vertical Flip",
                "help": "Flip the image vertically",
            },
        },
        "controls": {
            "_label": "Camera Controls",
            "_is_object": True,
            "af_mode": {
                "type": "enum",
                "options": [
                    {"value": 0, "label": "Manual"},
                    {"value": 1, "label": "Single AF"},
                    {"value": 2, "label": "Continuous AF"},
                ],
                "label": "Autofocus Mode",
                "help": "Autofocus mode (if camera supports)",
            },
            "lens_position": {
                "type": "number",
                "min": 0,
                "max": 10,
                "step": 0.1,
                "label": "Lens Position",
                "help": "Manual lens focus position (0 = infinity)",
            },
        },
    },
    "output": {
        "_label": "Output Settings",
        "_description": "Image output directory, naming, and quality",
        "_order": 3,
        "directory": {
            "type": "path",
            "label": "Output Directory",
            "help": "Base directory for saved images",
        },
        "filename_pattern": {
            "type": "text",
            "label": "Filename Pattern",
            "help": "Pattern with strftime directives: {name}, {timestamp}, {counter}, %Y%m%d_%H%M%S",
        },
        "project_name": {
            "type": "text",
            "label": "Project Name",
            "help": "Used in filename pattern as {name}",
        },
        "quality": {
            "type": "slider",
            "min": 0,
            "max": 100,
            "step": 1,
            "label": "JPEG Quality",
            "help": "Image quality (0-100). Higher = better quality, larger files",
        },
        "organize_by_date": {
            "type": "boolean",
            "label": "Organize by Date",
            "help": "Create YEAR/MONTH/DAY subdirectories",
        },
        "date_format": {
            "type": "text",
            "label": "Date Format",
            "help": "Strftime format for subdirectories (e.g., %Y/%m/%d)",
        },
        "symlink_latest": {
            "_label": "Symlink Latest",
            "_is_object": True,
            "enabled": {
                "type": "boolean",
                "label": "Enable Symlink",
                "help": "Create a symlink to the latest image",
            },
            "path": {
                "type": "path",
                "label": "Symlink Path",
                "help": "Path for the latest image symlink",
                "_depends_on": "output.symlink_latest.enabled",
            },
        },
    },
    "video": {
        "_label": "Video Settings",
        "_description": "Timelapse video output and codec settings",
        "_order": 4,
        "directory": {
            "type": "path",
            "label": "Video Directory",
            "help": "Directory for generated timelapse videos",
        },
        "organize_by_date": {
            "type": "boolean",
            "label": "Organize by Date",
            "help": "Create date subdirectories for videos",
        },
        "date_format": {
            "type": "text",
            "label": "Date Format",
            "help": "Strftime format for subdirectories",
        },
        "filename_pattern": {
            "type": "text",
            "label": "Filename Pattern",
            "help": "Pattern: {name}, {start_date}, {end_date}",
        },
        "codec": {
            "_label": "Codec Settings",
            "_is_object": True,
            "name": {
                "type": "enum",
                "options": [
                    {"value": "libx264", "label": "H.264 (libx264)"},
                    {"value": "libx265", "label": "H.265/HEVC (libx265)"},
                ],
                "label": "Video Codec",
                "help": "Video compression codec",
            },
            "pixel_format": {
                "type": "enum",
                "options": [
                    {"value": "yuv420p", "label": "YUV 4:2:0 (Max Compatibility)"},
                    {"value": "yuv444p", "label": "YUV 4:4:4"},
                ],
                "label": "Pixel Format",
                "help": "yuv420p for maximum compatibility",
            },
            "crf": {
                "type": "slider",
                "min": 0,
                "max": 51,
                "step": 1,
                "label": "CRF (Quality)",
                "help": "Constant Rate Factor: 0-51, lower = better quality. 18-23 recommended",
            },
        },
        "fps": {
            "type": "number",
            "min": 1,
            "max": 60,
            "step": 1,
            "label": "Frame Rate (FPS)",
            "help": "Frames per second: 24 (cinematic), 25 (PAL), 30 (NTSC)",
        },
    },
    "timelapse": {
        "_label": "Timelapse Settings",
        "_description": "Basic timelapse capture settings",
        "_order": 5,
        "interval": {
            "type": "number",
            "min": 1,
            "max": 3600,
            "step": 1,
            "label": "Capture Interval",
            "help": "Seconds between captures",
        },
        "num_frames": {
            "type": "number",
            "min": 0,
            "max": 100000,
            "step": 1,
            "label": "Number of Frames",
            "help": "Total frames to capture (0 = unlimited)",
        },
        "stabilization_delay": {
            "type": "number",
            "min": 0,
            "max": 30,
            "step": 0.5,
            "label": "Stabilization Delay",
            "help": "Seconds to wait after camera start",
        },
    },
    "adaptive_timelapse": {
        "_label": "Adaptive Timelapse",
        "_description": "Auto-exposure based on light conditions (for auto_timelapse.py)",
        "_order": 6,
        "enabled": {
            "type": "boolean",
            "label": "Enable Adaptive Mode",
            "help": "Enable adaptive exposure based on light conditions",
        },
        "interval": {
            "type": "number",
            "min": 1,
            "max": 3600,
            "step": 1,
            "label": "Capture Interval",
            "help": "Seconds between captures",
        },
        "reference_lux": {
            "type": "number",
            "min": 0,
            "max": 100,
            "step": 0.1,
            "label": "Reference Lux",
            "help": "Reference light level for calculations",
        },
        "direct_brightness_control": {
            "type": "boolean",
            "label": "Direct Brightness Control",
            "help": "Bypasses ML for simple physics-based exposure",
        },
        "brightness_damping": {
            "type": "slider",
            "min": 0,
            "max": 1,
            "step": 0.05,
            "label": "Brightness Damping",
            "help": "Damping factor for brightness corrections (0.5 = 50% per frame)",
        },
        "num_frames": {
            "type": "number",
            "min": 0,
            "max": 100000,
            "step": 1,
            "label": "Number of Frames",
            "help": "Total frames (0 = unlimited, runs continuously)",
        },
        "light_thresholds": {
            "_label": "Light Thresholds",
            "_is_object": True,
            "night": {
                "type": "number",
                "min": 0,
                "max": 100,
                "step": 1,
                "label": "Night Threshold",
                "help": "Lux below this = night mode",
            },
            "day": {
                "type": "number",
                "min": 0,
                "max": 1000,
                "step": 1,
                "label": "Day Threshold",
                "help": "Lux above this = day mode",
            },
        },
        "night_mode": {
            "_label": "Night Mode",
            "_is_object": True,
            "_depends_on": "adaptive_timelapse.enabled",
            "max_exposure_time": {
                "type": "number",
                "min": 0.1,
                "max": 60,
                "step": 0.1,
                "label": "Max Exposure Time",
                "help": "Maximum exposure in seconds (limit to avoid star trails)",
            },
            "analogue_gain": {
                "type": "slider",
                "min": 1,
                "max": 16,
                "step": 0.5,
                "label": "Analogue Gain",
                "help": "ISO equivalent. Higher = brighter but noisier",
            },
            "awb_enable": {
                "type": "boolean",
                "label": "Auto White Balance",
                "help": "Enable automatic white balance",
            },
            "colour_gains": {
                "_label": "Color Gains",
                "_is_array": True,
                "_array_length": 2,
                "type": "number",
                "min": 0,
                "max": 5,
                "step": 0.01,
                "label": "Color Gains [Red, Blue]",
                "help": "Manual color gains if AWB disabled",
            },
        },
        "day_mode": {
            "_label": "Day Mode",
            "_is_object": True,
            "_depends_on": "adaptive_timelapse.enabled",
            "exposure_time": {
                "type": "number",
                "min": 0.0001,
                "max": 1,
                "step": 0.001,
                "label": "Exposure Time",
                "help": "Exposure time in seconds",
            },
            "analogue_gain": {
                "type": "slider",
                "min": 1,
                "max": 8,
                "step": 0.5,
                "label": "Analogue Gain",
                "help": "Lower = less noise in daylight",
            },
            "awb_enable": {
                "type": "boolean",
                "label": "Auto White Balance",
                "help": "Enable automatic white balance",
            },
        },
        "transition_mode": {
            "_label": "Transition Mode (Dawn/Dusk)",
            "_is_object": True,
            "_depends_on": "adaptive_timelapse.enabled",
            "smooth_transition": {
                "type": "boolean",
                "label": "Smooth Transition",
                "help": "Gradually adjust between day/night settings",
            },
            "sequential_ramping": {
                "type": "boolean",
                "label": "Sequential Ramping",
                "help": "Adjust shutter first, then gain (reduces noise)",
            },
            "lux_smoothing_factor": {
                "type": "slider",
                "min": 0,
                "max": 1,
                "step": 0.05,
                "label": "Lux Smoothing",
                "help": "Smoothing factor for lux readings",
            },
            "hysteresis_frames": {
                "type": "number",
                "min": 0,
                "max": 20,
                "step": 1,
                "label": "Hysteresis Frames",
                "help": "Frames before mode switch to prevent flicker",
            },
            "wb_transition_speed": {
                "type": "slider",
                "min": 0,
                "max": 1,
                "step": 0.05,
                "label": "WB Transition Speed",
                "help": "White balance adjustment speed",
            },
            "gain_transition_speed": {
                "type": "slider",
                "min": 0,
                "max": 1,
                "step": 0.05,
                "label": "Gain Transition Speed",
                "help": "Gain adjustment speed",
            },
            "exposure_transition_speed": {
                "type": "slider",
                "min": 0,
                "max": 1,
                "step": 0.05,
                "label": "Exposure Transition Speed",
                "help": "Exposure adjustment speed",
            },
            "smooth_wb_in_day_mode": {
                "type": "boolean",
                "label": "Smooth WB in Day Mode",
                "help": "Apply smooth WB transitions in day mode",
            },
            "smooth_exposure_in_day_mode": {
                "type": "boolean",
                "label": "Smooth Exposure in Day Mode",
                "help": "Apply smooth exposure transitions in day mode",
            },
            "fast_rampdown_speed": {
                "type": "slider",
                "min": 0,
                "max": 1,
                "step": 0.05,
                "label": "Fast Rampdown Speed",
                "help": "Speed for overexposure correction",
            },
            "fast_rampup_speed": {
                "type": "slider",
                "min": 0,
                "max": 1,
                "step": 0.05,
                "label": "Fast Rampup Speed",
                "help": "Speed for underexposure recovery",
            },
            "brightness_feedback_enabled": {
                "type": "boolean",
                "label": "Brightness Feedback",
                "help": "Enable sustained drift correction",
            },
            "target_brightness": {
                "type": "number",
                "min": 0,
                "max": 255,
                "step": 1,
                "label": "Target Brightness",
                "help": "Target brightness value (0-255)",
            },
            "brightness_tolerance": {
                "type": "number",
                "min": 0,
                "max": 100,
                "step": 1,
                "label": "Brightness Tolerance",
                "help": "Tolerance range around target",
            },
            "brightness_feedback_strength": {
                "type": "slider",
                "min": 0,
                "max": 1,
                "step": 0.05,
                "label": "Feedback Strength",
                "help": "Brightness correction strength",
            },
        },
        "test_shot": {
            "_label": "Test Shot Settings",
            "_is_object": True,
            "_depends_on": "adaptive_timelapse.enabled",
            "enabled": {
                "type": "boolean",
                "label": "Enable Test Shots",
                "help": "Take test shot before capture to measure light",
            },
            "exposure_time": {
                "type": "number",
                "min": 0.01,
                "max": 1,
                "step": 0.01,
                "label": "Test Exposure Time",
                "help": "Quick test shot exposure time in seconds",
            },
            "analogue_gain": {
                "type": "number",
                "min": 1,
                "max": 8,
                "step": 0.5,
                "label": "Test Gain",
                "help": "Gain for test shots",
            },
            "frequency": {
                "type": "number",
                "min": 1,
                "max": 10,
                "step": 1,
                "label": "Frequency",
                "help": "Test shot every N captures",
            },
        },
        "diagnostics": {
            "_label": "Diagnostics",
            "_is_object": True,
            "enabled": {
                "type": "boolean",
                "label": "Enable Diagnostics",
                "help": "Save diagnostic metadata for debugging",
            },
        },
        "ml_exposure": {
            "_label": "ML Exposure Prediction",
            "_is_object": True,
            "_depends_on": "adaptive_timelapse.enabled",
            "enabled": {
                "type": "boolean",
                "label": "Enable ML Exposure",
                "help": "Use machine learning for exposure prediction",
            },
            "initial_trust_v2": {
                "type": "slider",
                "min": 0,
                "max": 1,
                "step": 0.05,
                "label": "Initial Trust",
                "help": "Baseline trust in ML predictions",
            },
            "max_trust": {
                "type": "slider",
                "min": 0,
                "max": 1,
                "step": 0.05,
                "label": "Max Trust",
                "help": "Maximum trust level when confident",
            },
            "good_brightness_min": {
                "type": "number",
                "min": 0,
                "max": 255,
                "step": 1,
                "label": "Good Brightness Min",
                "help": "Minimum brightness for good predictions",
            },
            "good_brightness_max": {
                "type": "number",
                "min": 0,
                "max": 255,
                "step": 1,
                "label": "Good Brightness Max",
                "help": "Maximum brightness for good predictions",
            },
        },
    },
    "system": {
        "_label": "System Settings",
        "_description": "Directory creation and metadata handling",
        "_order": 7,
        "create_directories": {
            "type": "boolean",
            "label": "Create Directories",
            "help": "Automatically create output directories if missing",
        },
        "save_metadata": {
            "type": "boolean",
            "label": "Save Metadata",
            "help": "Save metadata JSON with each capture",
        },
        "metadata_filename": {
            "type": "text",
            "label": "Metadata Filename",
            "help": "Pattern for metadata files",
        },
        "metadata_folder": {
            "type": "text",
            "label": "Metadata Folder",
            "help": "Folder for test shot metadata (overwritten each time)",
        },
    },
    "overlay": {
        "_label": "Overlay Settings",
        "_description": "Text overlay on captured images",
        "_order": 8,
        "enabled": {
            "type": "boolean",
            "label": "Enable Overlay",
            "help": "Add text overlay to images",
        },
        "font": {
            "_label": "Font Settings",
            "_is_object": True,
            "_depends_on": "overlay.enabled",
            "family": {
                "type": "text",
                "label": "Font Family",
                "help": "Font name or path to .ttf file",
            },
            "size_ratio": {
                "type": "slider",
                "min": 0.01,
                "max": 0.1,
                "step": 0.002,
                "label": "Size Ratio",
                "help": "Font size relative to image height (0.02 = 2%)",
            },
            "color": {
                "type": "rgba",
                "label": "Font Color",
                "help": "Text color (RGBA)",
            },
        },
        "background": {
            "_label": "Background Settings",
            "_is_object": True,
            "_depends_on": "overlay.enabled",
            "enabled": {
                "type": "boolean",
                "label": "Enable Background",
                "help": "Show semi-transparent background behind text",
            },
            "color": {
                "type": "rgba",
                "label": "Background Color",
                "help": "Background color (RGBA, last value is opacity)",
            },
            "padding": {
                "type": "slider",
                "min": 0,
                "max": 2,
                "step": 0.1,
                "label": "Padding",
                "help": "Padding around text (relative to font size)",
            },
        },
        "position": {
            "type": "enum",
            "options": [
                {"value": "top-left", "label": "Top Left"},
                {"value": "top-right", "label": "Top Right"},
                {"value": "bottom-left", "label": "Bottom Left"},
                {"value": "bottom-right", "label": "Bottom Right"},
                {"value": "top-bar", "label": "Top Bar (Full Width)"},
                {"value": "custom", "label": "Custom Position"},
            ],
            "label": "Position",
            "help": "Where to place the overlay",
            "_depends_on": "overlay.enabled",
        },
        "custom_position": {
            "_label": "Custom Position",
            "_is_object": True,
            "_depends_on": "overlay.position",
            "_depends_on_value": "custom",
            "x": {
                "type": "slider",
                "min": 0,
                "max": 100,
                "step": 1,
                "label": "X Position (%)",
                "help": "Horizontal position (% from left)",
            },
            "y": {
                "type": "slider",
                "min": 0,
                "max": 100,
                "step": 1,
                "label": "Y Position (%)",
                "help": "Vertical position (% from top)",
            },
        },
        "margin": {
            "type": "number",
            "min": 0,
            "max": 100,
            "step": 1,
            "label": "Margin",
            "help": "Margin from edges in pixels",
            "_depends_on": "overlay.enabled",
        },
        "content": {
            "_label": "Content Templates",
            "_is_object": True,
            "_depends_on": "overlay.enabled",
            "line_1_left": {
                "type": "text",
                "label": "Line 1 Left",
                "help": "Template for line 1 left side",
            },
            "line_1_right": {
                "type": "text",
                "label": "Line 1 Right",
                "help": "Template for line 1 right side",
            },
            "line_2_left": {
                "type": "text",
                "label": "Line 2 Left",
                "help": "Template for line 2 left side",
            },
            "line_2_right": {
                "type": "text",
                "label": "Line 2 Right",
                "help": "Template for line 2 right side",
            },
        },
        "camera_name": {
            "type": "text",
            "label": "Camera Name",
            "help": "Name displayed in overlay as {camera_name}",
            "_depends_on": "overlay.enabled",
        },
        "datetime": {
            "_label": "DateTime Formatting",
            "_is_object": True,
            "_depends_on": "overlay.enabled",
            "localized": {
                "type": "boolean",
                "label": "Use Localized Format",
                "help": "Use local language for day/month names",
            },
            "locale": {
                "type": "text",
                "label": "Locale",
                "help": "Locale code (e.g., nb_NO.UTF-8)",
            },
            "show_seconds": {
                "type": "boolean",
                "label": "Show Seconds",
                "help": "Include seconds in time display",
            },
            "date_format": {
                "type": "text",
                "label": "Date Format",
                "help": "Strftime format for date",
            },
            "time_format": {
                "type": "text",
                "label": "Time Format",
                "help": "Strftime format for time",
            },
        },
        "layout": {
            "_label": "Layout Options",
            "_is_object": True,
            "_depends_on": "overlay.enabled",
            "line_spacing": {
                "type": "slider",
                "min": 0.5,
                "max": 3,
                "step": 0.1,
                "label": "Line Spacing",
                "help": "Multiplier for line spacing (1.0 = normal)",
            },
            "section_spacing": {
                "type": "boolean",
                "label": "Section Spacing",
                "help": "Add blank line between sections",
            },
            "bottom_padding_multiplier": {
                "type": "slider",
                "min": 0,
                "max": 2,
                "step": 0.1,
                "label": "Bottom Padding",
                "help": "Extra padding below text (multiplier)",
            },
        },
    },
    "logging": {
        "_label": "Logging Settings",
        "_description": "Log file configuration",
        "_order": 9,
        "enabled": {
            "type": "boolean",
            "label": "Enable Logging",
            "help": "Enable logging to file",
        },
        "level": {
            "type": "enum",
            "options": [
                {"value": "DEBUG", "label": "DEBUG"},
                {"value": "INFO", "label": "INFO"},
                {"value": "WARNING", "label": "WARNING"},
                {"value": "ERROR", "label": "ERROR"},
                {"value": "CRITICAL", "label": "CRITICAL"},
            ],
            "label": "Log Level",
            "help": "Minimum log level to record",
            "_depends_on": "logging.enabled",
        },
        "log_file": {
            "type": "path",
            "label": "Log File Path",
            "help": "Path pattern with {script} placeholder",
            "_depends_on": "logging.enabled",
        },
        "format": {
            "type": "text",
            "label": "Log Format",
            "help": "Python logging format string",
            "_depends_on": "logging.enabled",
        },
        "date_format": {
            "type": "text",
            "label": "Date Format",
            "help": "Strftime format for timestamps",
            "_depends_on": "logging.enabled",
        },
        "console": {
            "type": "boolean",
            "label": "Console Output",
            "help": "Also log to console/terminal",
            "_depends_on": "logging.enabled",
        },
        "max_size_mb": {
            "type": "number",
            "min": 0,
            "max": 1000,
            "step": 1,
            "label": "Max Size (MB)",
            "help": "Maximum log file size (0 = unlimited)",
            "_depends_on": "logging.enabled",
        },
        "backup_count": {
            "type": "number",
            "min": 0,
            "max": 100,
            "step": 1,
            "label": "Backup Count",
            "help": "Number of backup log files to keep",
            "_depends_on": "logging.enabled",
        },
    },
    "graphs": {
        "_label": "Graphs Settings",
        "_description": "Analysis graph generation settings",
        "_order": 10,
        "directory": {
            "type": "path",
            "label": "Graph Directory",
            "help": "Directory for generated graphs",
        },
        "width": {
            "type": "number",
            "min": 4,
            "max": 24,
            "step": 1,
            "label": "Width (inches)",
            "help": "Graph width in inches",
        },
        "height": {
            "type": "number",
            "min": 3,
            "max": 16,
            "step": 1,
            "label": "Height (inches)",
            "help": "Graph height in inches",
        },
        "dpi": {
            "type": "number",
            "min": 72,
            "max": 300,
            "step": 1,
            "label": "DPI",
            "help": "Resolution (dots per inch)",
        },
        "default_hours": {
            "type": "number",
            "min": 1,
            "max": 168,
            "step": 1,
            "label": "Default Hours",
            "help": "Default time window for analysis",
        },
    },
    "video_upload": {
        "_label": "Video Upload Settings",
        "_description": "Automatic video upload after timelapse creation",
        "_order": 11,
        "enabled": {
            "type": "boolean",
            "label": "Enable Upload",
            "help": "Automatically upload videos after creation",
        },
        "url": {
            "type": "text",
            "label": "Upload URL",
            "help": "Server endpoint for video uploads",
            "_depends_on": "video_upload.enabled",
        },
        "api_key": {
            "type": "password",
            "label": "API Key",
            "help": "Bearer token for authentication",
            "_depends_on": "video_upload.enabled",
        },
        "camera_id": {
            "type": "text",
            "label": "Camera ID",
            "help": "Identifier for this camera on the server",
            "_depends_on": "video_upload.enabled",
        },
    },
    "weather": {
        "_label": "Weather Settings",
        "_description": "Weather data fetching from Netatmo API",
        "_order": 12,
        "enabled": {
            "type": "boolean",
            "label": "Enable Weather",
            "help": "Fetch weather data for overlay",
        },
        "endpoint": {
            "type": "text",
            "label": "API Endpoint",
            "help": "Netatmo API endpoint URL",
            "_depends_on": "weather.enabled",
        },
        "cache_duration": {
            "type": "number",
            "min": 60,
            "max": 3600,
            "step": 60,
            "label": "Cache Duration",
            "help": "Seconds to cache weather data before refresh",
            "_depends_on": "weather.enabled",
        },
        "timeout": {
            "type": "number",
            "min": 1,
            "max": 30,
            "step": 1,
            "label": "Timeout",
            "help": "Request timeout in seconds",
            "_depends_on": "weather.enabled",
        },
    },
    "database": {
        "_label": "Database Settings",
        "_description": "SQLite storage for metadata and analysis",
        "_order": 13,
        "enabled": {
            "type": "boolean",
            "label": "Enable Database",
            "help": "Store capture data in SQLite for analysis",
        },
        "path": {
            "type": "path",
            "label": "Database Path",
            "help": "Path to SQLite database file",
            "_depends_on": "database.enabled",
        },
        "create_directories": {
            "type": "boolean",
            "label": "Create Directories",
            "help": "Create data directory if missing",
            "_depends_on": "database.enabled",
        },
    },
    "barentswatch": {
        "_label": "Barentswatch Settings",
        "_description": "Ship tracking data from Barentswatch",
        "_order": 14,
        "enabled": {
            "type": "boolean",
            "label": "Enable Barentswatch",
            "help": "Include ship tracking data in overlay",
        },
        "ships_file": {
            "type": "path",
            "label": "Ships File",
            "help": "Path to ships JSON data file",
            "_depends_on": "barentswatch.enabled",
        },
    },
    "tide": {
        "_label": "Tide Settings",
        "_description": "Tide level data",
        "_order": 15,
        "enabled": {
            "type": "boolean",
            "label": "Enable Tide",
            "help": "Include tide data in overlay",
        },
        "tide_file": {
            "type": "path",
            "label": "Tide File",
            "help": "Path to tide JSON data file",
            "_depends_on": "tide.enabled",
        },
    },
    "aurora": {
        "_label": "Aurora Settings",
        "_description": "Aurora forecast data",
        "_order": 16,
        "enabled": {
            "type": "boolean",
            "label": "Enable Aurora",
            "help": "Include aurora forecast in overlay",
        },
        "aurora_file": {
            "type": "path",
            "label": "Aurora File",
            "help": "Path to aurora JSON data file",
            "_depends_on": "aurora.enabled",
        },
    },
}


def get_schema():
    """Return the config schema."""
    return CONFIG_SCHEMA


def get_section_order():
    """Return sections in display order."""
    sections = []
    for key, value in CONFIG_SCHEMA.items():
        if isinstance(value, dict) and "_order" in value:
            sections.append((key, value.get("_order", 999)))
    sections.sort(key=lambda x: x[1])
    return [s[0] for s in sections]
